config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers => { registrations: 'registrations' }
  
  resources :countries
  
  resources :events do
    member do
      post 'join'
      post 'leave' 
    end
    collection do
      get 'subscribed'
    end
  end
  
  resources :matches
  
  resources :players do
    resources :bets, shallow: true # index/new/create are nested
  end
  
  root 'static_pages#home'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home

  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="page-header">
  <h1>Bienvenue sur Bets!</h1>
</div>
<% if player_signed_in? %>
<div class="row">
  <%= render partial: 'shared/thumbnail', 
  		locals: {the_link: edit_player_path(current_player), name:"Editer pronostics", icon: "fa-futbol-o", color: "red"}%>
  <%= render partial: 'shared/thumbnail', 
  		locals: {the_link: events_path, name:"Voir les groupes", icon: "fa-users", color: "blue"}%>
  <%= render partial: 'shared/thumbnail', 
  		locals: {the_link: matches_path, name:"Voir les matchs", icon: "fa fa-trophy", color: "gold"}%>
</div>
  <% else %>
  <p>Inscrivez-vous ou identifiez-vous pour accéder à vos pronos.</p>
  <%= link_to "S'identifier", new_player_session_path,  class: "btn btn-primary btn-lg" %>
  <%= link_to "S'inscrire", new_player_registration_path, class: "btn btn-primary btn-lg" %>
<% end %>