config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers => { registrations: 'registrations' }
  
  resources :countries
  
  resources :events do
    member do
      post 'join'
      post 'leave' 
    end
    collection do
      get 'subscribed'
    end
  end
  
  resources :matches
  
  resources :players do
    resources :bets, shallow: true # index/new/create are nested
  end
  
  root 'static_pages#home'
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :players
  belongs_to :owner_player, class_name: "Player"
  
  validates :name, presence: true, uniqueness: true
  validates :owner_player, presence: true

  after_create :add_owner_player_to_players
  
  scope :is_not_member, ->(player){ where('id NOT IN (?)', ([-1] << Event.is_member(player).pluck(:id)).flatten) }
  scope :is_member, ->(player){ joins(:events_players).where("events_players.player_id = ?",player.id)}
  scope :is_owner, ->(player){ where("owner_player_id = ?",player.id)} # the user created this groupe
  
  STATUS_REGISTERING = "Inscriptions"
  STATUS_STARTED= "Commencé"
  STATUS_FINISHED= "Terminé"
  
  def player_count
    Player.subscribed_to(self).count
  end
  
  def is_owner?(player)
    return owner_player == player
  end
  
  def status
   STATUS_REGISTERING
   # if Time.now < self.start_date
   #   STATUS_REGISTERING
   # else
   #    STATUS_STARTED
   # end
  end
  
  private
    def add_owner_player_to_players
      if !owner_player.events.include? self
        owner_player.events << self
      end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_player!
  before_action :set_event, only: [:join,:leave,:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index    
    set_index_variables
  end
  
  def subscribed
    set_index_variables
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @players = @event.players.order('points DESC')
  end

  # A player join this group
  def join
    if @event.password.present? 
       # make sure the provided password matches:
       unless event_params && event_params[:password] == @event.password
         flash[:notice] = "Mot de passe incorrect !"
         redirect_to action: 'index'
         return
       end
    end
    
    current_player.events << @event
    flash[:success] = "Vous avez rejoint ce groupe !"
    redirect_to @event
  end
  
  def leave
    set_index_variables
    if @event.is_owner?(current_player)
      flash[:notice] = "Vous ne pouvez pas quitter un groupe que vous avez créé!"
      redirect_to action: "index"
    elsif current_player.events.include? @event
      current_player.events.delete(@event)
      flash[:notice] = "Vous avez quitté ce groupe !"
      redirect_to action: "index"
    else
      flash[:error] = "Vous n'êtes pas membre de ce groupe."
      redirect_to action: "index"
    end
  end
  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Le groupe '#{@event.name}' a été créé!" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    if( @event.owner_player != current_player )
      respond_to do |format|
       format.html { redirect_to events_url, notice: 'Vous n\'etes pas le propriétaire de cet event.' }
       format.json { head :no_content }
      end
    end
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:password, :name, :start_date, :owner_player_id)
    end
    
    def set_index_variables
      @subscribed_events     = Event.is_member(current_player)
      @not_subscribed_events = Event.is_not_member(current_player)
      @owner_events          = Event.is_owner(current_player)
    end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :owner_player_id, value: current_player.id %>
  <div class="input-group input-group-lg">
    <%= f.label :name, "Nom du groupe", class: "input-group-addon" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="input-group input-group-lg">
    <%= f.label :password,"Mot de passe: Laisser vide pour créer un groupe ouvert", class: "input-group-addon" %>
    <%= f.text_field :password, autofocus: true, class: "form-control" %>
  </div>
  

  <div class="actions">
    <%= f.submit "Créer le groupe", class: "btn btn-complete"%>
  </div>
<% end %>

app/views/events/_join_modal.html.erb
<!-- Modal -->
<%= tag("div", id:"myModal-#{event.id}", class:"modal fade", role:"dialog") %>
  <div class="modal-dialog modal-sm">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <% if event.password.present? %>
        <h4 class="modal-title">Groupe privé</h4>
        <% else %>
        <h4 class="modal-title">Groupe public</h4>
        <% end %>
      </div>
      <div class="modal-body">
        <p>Rejoindre le groupe '<%= event.name %>'.</p>
        <%= form_tag( join_event_path(event), method: :post) do %>
          <% if event.password.present? %>
          	<div class="input-group input-group-lg">
			  <%= label_tag :password,"Mot de passe", class: "input-group-addon" %>
			  <%= text_field_tag 'event[password]', '', placeholder: "entrer le mot de passe", autofocus: true, class: "form-control" %>
			</div>
          <% end %>
          <%= submit_tag 'Rejoindre', class: "btn btn-complete" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= link_to 'Créer un nouveau groupe', new_event_path, class: "btn btn-primary" %>
</div>

<h2>Les groupes dont vous faites partie</h2>

<table class="table table-bordered"">
  <thead>
    <tr>
      <th class="centered">Nom du groupe</th>
      <th class="centered">Statut</th>
      <th class="centered">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @subscribed_events.each do |event| %>
      <tr>
        <td class="centered"><%= link_to "#{event.name} (#{event.player_count})", event %></td>
        <td class="centered"><%= event.status %></td>
        <td class="centered" ><%= link_to "Quitter le groupe", leave_event_path(event), method: :post, class: "btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>    
 
<h2>Rejoignez d'autres groupes</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="centered">Name</th>
      <th class="centered">Statut</th>
      <th class="centered">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @not_subscribed_events.each do |event| %>
      <tr>
        <td class="centered"><%= link_to "#{event.name} (#{event.player_count})", event %></td>
        <td class="centered"><%= event.password.blank? ? tag("i",class:'fa fa-unlock') : tag("i",class:'fa fa-lock') %></td>
		<td class="centered"><%= tag("button", type:"button", class:"btn btn-info btn-lg", "data-toggle": "modal", "data-target":"#myModal-#{event.id}",open:"true") %>Rejoindre</button></td>
      </tr>
      <%= render partial: 'join_modal', locals: {event: event} %>
    <% end %>
  </tbody>
</table>

<h2>Les groupes que vous avez créés</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="centered">Name</th>
      <th class="centered">Statut</th>
      <th class="centered" colspan=2>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @owner_events.each do |event| %>
      <tr>
        <td class="centered"><%= link_to "#{event.name} (#{event.player_count})", event %></td>
        <td class="centered"><%= event.status %></td>
        <td class="centered"><%= link_to 'Modifier', edit_event_path(event), class: "btn btn-default" %>
        <%= link_to 'Effacer', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="4"><%= link_to 'Créer un nouveau groupe', new_event_path, class: "btn btn-primary" %>
    </tr>	
  </tbody>
</table>

app/views/events/new.html.erb
<h1>Créer un nouveau groupe</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @event.name %><small> (Admin: <%= @event.owner_player.name %>)</small></h1>

<%= pluralize(@players.count, 'Participant') %>
<table class="table table-bordered">
  <thead>
  	<td class="centered">Classement</td>
	<td class="centered">Nom</td>
	<td class="centered">Points</td>
  </thead>
  <tbody>
  	<% points = @players.pluck(:points).uniq %> <!-- Players is already sorted -->
    <% @players.each_with_index do |p,i| %>
	  <tr>
	  	<% rank = points.index(p.points) %>
	  	<td class="centered"><%= tag("i",class:"fa fa-trophy rank-#{rank} fa-2x") if rank <= 2 %><%= "##{1+rank}" %></td>
		<td class="centered"><%= p.name %> (<%= link_to( 'voir pronostics', p ) %>)</td>
		<td class="centered"><%= p.count_points %></td>	
	  </tr>
	<% end %>
	</tbody>
</table>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/subscribed.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= link_to 'Créer un nouveau groupe', new_event_path, class: "btn btn-primary" %>
</div>

<h2>Les groupes dont vous faites partie</h2>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Nom du groupe</th>
      <th>Statut</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @subscribed_events.each do |event| %>
      <tr>
        <td><%= link_to "#{event.name} (#{event.player_count})", event %></td>
        <td><%= event.status %></td>
        <td><%= link_to "Quitter le groupe", leave_event_path(event), method: :post, class: "btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>