config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers => { registrations: 'registrations' }
  
  resources :countries
  
  resources :events do
    member do
      post 'join'
      post 'leave' 
    end
    collection do
      get 'subscribed'
    end
  end
  
  resources :matches
  
  resources :players do
    resources :bets, shallow: true # index/new/create are nested
  end
  
  root 'static_pages#home'
  

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :bets
  has_and_belongs_to_many :events

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  
  before_create :setup_player
  
  accepts_nested_attributes_for :bets
  
  # Strange my .joins(:events_players) doesn't seem to work here.
  sql = "SELECT \"players\".* FROM \"players\" INNER JOIN \"events_players\" ON \"events_players\".\"player_id\" = \"players\".\"id\""
  scope :joins_events_players, -> { all }
  scope :subscribed_to, ->(event){ joins(:events).where("events_players.event_id = ?",event.id)}  
  
  def count_points
    score = 0
    self.bets.each do |bet|
      score += 1 if bet.won
    end
    return score
  end
  
  private
    # Add the bets and setup the points
    def setup_player
      self.points = 0
      Match.all.each do |m|
        self.bets.build(match: m, result: Match::TIE)
      end
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_player!
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all #Player.for_event(@current_player.event)
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @bets = @player.bets.joins(:match).order('matches.date ASC')
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
    #Make sure only the logged-in user can edit himself.
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    # TODO create and redirect to a page for that
    @player.name  = "Jéjé"
    

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    if @player != current_player
      respond_to do |format|
        format.html { redirect_to @player, notice: 'Vous ne pouvez pas modifier un autre utilisateur.' }
        return
      end
    end
    
    params_bets = { :bets_attributes => {} }
    player_params[:bets_attributes].each do |k,v|
      b = Bet.find_by_id(v['id'])
      params_bets[:bets_attributes][k] = v if b.match.present? && b.match.date > Time.now 
    end
    
    
    respond_to do |format|
      if @player.update(params_bets)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy_disabled
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player    
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(
        :name,
        :points,
        :bets_attributes => [:result, :id])
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  	<% @player.bets.joins(:match).order("date ASC").each do |bet| %>
      <%= f.fields_for :bets, bet do |b| %>
	    <div class="col-md-12">
	      <div class="col-md-3">
	      	  <% match = bet.match %>
		      <% iso = Country.find_by_name(match.host_name).try(:iso) || 'hk' %>
			  <div class="col-xs-5 text-left"><%= image_tag "country-4x3/#{iso}.svg", width: 64, alt: 'HK' %></div>
			  <div class="col-xs-2 text-center">VS</div>
			  <% iso = Country.find_by_name(match.guest_name).try(:iso) || 'hk' %>
			  <div class="col-xs-5 text-right"><%= image_tag "country-4x3/#{iso}.svg", width: 64, alt: 'HK' %></div>
			  
		  </div>
		  <div class="col-md-9" >
		    <div class="buttonset">
		      <%= b.label("result_g", "victoire de #{b.object.match.host_name}",class:"col-xs-4",style:"min-height:50px;","data-toggle":"tooltip", "title":"88% des choix") %>
		      <%= b.radio_button(:result, Match::WIN) %>
		      <%= b.label("result_n", "Match nul",class:"col-xs-4",style:"min-height:50px;","data-toggle":"tooltip", "title":"88% des choix") %>
		      <%= b.radio_button(:result, Match::TIE) %>
		      <%= b.label("result_p", "victoire de #{b.object.match.guest_name}",class:"col-xs-4",style:"min-height:50px;","data-toggle":"tooltip", "title":"88% des choix") %>
		      <%= b.radio_button(:result, Match::LOSE) %>
		    </div>
		  </div>
	    </div>
	  <% end %>
  <% end %>  
  
  <div class="actions">
    <%= f.submit "Enregistrer", class:"btn btn-complete" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Déterminez vos pronostics</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.points %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Points:</strong>
  <%= @player.count_points %>
</p>

<ul>
	<li>
	  <%@bets.each_with_index do |b,i| %>
	    <%= i %>
	    <%= render b %>
	  <% end %>
	</li>
</ul>
<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>