config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers => { registrations: 'registrations' }
  
  resources :countries
  
  resources :events do
    member do
      post 'join'
      post 'leave' 
    end
    collection do
      get 'subscribed'
    end
  end
  
  resources :matches
  
  resources :players do
    resources :bets, shallow: true # index/new/create are nested
  end
  
  root 'static_pages#home'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bets" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <link rel="stylesheet" href="/font-awesome-4.6.2/css/font-awesome.min.css">

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
  	<div class="masthead">	</div>
    <div class="navbar navbar-default">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Bets</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
              <li><%= link_to "Editer pronostics", edit_player_path(current_player) if player_signed_in? %></li>
              <li><%= link_to "Voir les groupes", events_path if player_signed_in? %></li>
              <li><%= link_to "Voir les matchs", matches_path  %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          	<% if player_signed_in? %>
			<li class="dropdown">
			  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_player.name %><span class="caret"></span></a>
			  <ul class="dropdown-menu">
			    <li><%= link_to "Editer le profil", edit_player_path(current_player) %></li>
			    <li><%= link_to "Se déconnecter", destroy_player_session_path, method: :delete %></li>			 
			  </ul>
			</li>
			<% else %>
              <li><%= link_to "S'identifier", new_player_session_path  %></li>
			<% end %>	
		  </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
          <%#= bootstrap_flash %>
          <div class = "jumbotron">
          	<%= yield %>
          </div>
        
      </div><!--/row-->

      <footer>
        <p>&copy; BandanaTech 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= link_to "Accueil", root_path %>
	<p class="notice"><%= notice %></p>       
	<p class="alert"><%= alert %></p>
	<%= yield %>
</body>
</html>